/*
 * Copyright (c) 2014 Agung Gugiaji <gugiaji.wordpress.com>
 * 
 * All rights reserved. No warranty, explicit or implicit, provided.
 *
 * Use it at your own risk.
 */

package controller;

import view.*;
import mvc.*;


import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JSeparator;

import java.util.*;

//Main JFrame as Form Controller
public class frmController extends javax.swing.JFrame {

    /**
     * Creates new form frmController
     */
    public frmController() {
        initComponents();
        ctrlMasterTrans.ActivateStaff();
        ctrlMasterTrans.ActivateLeave();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMaster = new javax.swing.JMenu();
        masStaffList = new javax.swing.JMenuItem();
        masAddStaff = new javax.swing.JMenuItem();
        masDelStaff = new javax.swing.JMenuItem();
        masAssignSup = new javax.swing.JMenuItem();
        masLeaveList = new javax.swing.JMenuItem();
        masAddLeave = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(100, 1000, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        mnuMaster.setText("Master");


        masStaffList.setText("Staff List");
        masStaffList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masStaffListActionPerformed(evt);
            }
        });
        mnuMaster.add(masStaffList);

        mnuMaster.add(new JSeparator());
        
        masAddStaff.setText("Add New Staff");
        masAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masAddStaffActionPerformed(evt);
            }
        });
        mnuMaster.add(masAddStaff);

        masDelStaff.setText("Delete Staff");
        masDelStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masDelStaffActionPerformed(evt);
            }
        });
        mnuMaster.add(masDelStaff);
        
        masAssignSup.setText("Assign Supervisor");
        masAssignSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masAssignSupActionPerformed(evt);
            }
        });
        mnuMaster.add(masAssignSup);
        
        mnuMaster.add(new JSeparator());
        mnuMaster.add(new JSeparator());
        
        masLeaveList.setText("Leave List");
        masLeaveList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masLeaveListActionPerformed(evt);
            }
        });
        mnuMaster.add(masLeaveList);

        mnuMaster.add(new JSeparator());
        masAddLeave.setText("Add New Leave");
        masAddLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masAddLeaveActionPerformed(evt);
            }
        });
        mnuMaster.add(masAddLeave);
        
        
        jMenuBar1.add(mnuMaster);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masStaffListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masProductListActionPerformed
        try {
            ArrayList<Staff> lststaff = ctrlMasterTrans.ListOfStaff();
            
            InternalFrmStaffList interfrm = new InternalFrmStaffList("Staff", lststaff);
            
            jDesktopPane1.add(interfrm);
            interfrm.setMaximum(true);
            interfrm.setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_masProductListActionPerformed
   
        
    private void masAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masAddProductActionPerformed
        // TODO add your handling code here:
        InternalFrmAddStaff interfrm = new InternalFrmAddStaff("Add new staff");
        jDesktopPane1.add(interfrm);
        interfrm.setSize(460, 300);
        interfrm.setVisible(true);
    }//GEN-LAST:event_masAddProductActionPerformed

    private void masDelStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masAddProductActionPerformed
        // TODO add your handling code here:
        InternalFrmDelStaff interfrm = new InternalFrmDelStaff("Delete staff");
        jDesktopPane1.add(interfrm);
        interfrm.setSize(360, 200);
        interfrm.setVisible(true);
    }
    
    private void masAssignSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masAddProductActionPerformed
        // TODO add your handling code here:
        InternalFrmAssignSup interfrm = new InternalFrmAssignSup("Assign Supervisor");
        jDesktopPane1.add(interfrm);
        interfrm.setSize(360, 200);
        interfrm.setVisible(true);
    }
    
    private void masLeaveListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masProductListActionPerformed
        try {
            ArrayList<Leave> lstleave = ctrlMasterTrans.ListOfLeave();
            ArrayList<Staff> lststaff = ctrlMasterTrans.ListOfStaff();
            
            InternalFrmLeaveList interfrm = new InternalFrmLeaveList("Leave", lstleave, lststaff);
            
            jDesktopPane1.add(interfrm);
            interfrm.setMaximum(true);
            interfrm.setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(frmController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void masAddLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masAddProductActionPerformed
        // TODO add your handling code here:
        InternalFrmAddLeave interfrm = new InternalFrmAddLeave("Add new leave");
        jDesktopPane1.add(interfrm);
        interfrm.setSize(460, 300);
        interfrm.setVisible(true);
    }
    
    public static void masApproveLeaveActionPerformed(String title, int leaveID) {//GEN-FIRST:event_masAddProductActionPerformed
        // TODO add your handling code here:
        InternalFrmApproveLeave interfrm = new InternalFrmApproveLeave(title, leaveID);
        jDesktopPane1.add(interfrm);
        interfrm.setSize(460, 300);
        interfrm.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem masAddStaff;
    private javax.swing.JMenuItem masDelStaff;
    private javax.swing.JMenuItem masAssignSup;
    private javax.swing.JMenuItem masStaffList;
    private javax.swing.JMenuItem masAddLeave;
    
    private javax.swing.JMenuItem masLeaveList;
    
    private javax.swing.JMenu mnuMaster;
    // End of variables declaration//GEN-END:variables
}
